repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --fix
        language: golang
        pass_filenames: false
      - id: go-unit-tests
        name: go-unit-tests
        description: Run unit tests.
        entry: go test ./...
        language: golang
        pass_filenames: false
